# feature-extraction

In [2]:
!pip install jovian --upgrade --quiet

In [3]:
import jovian

In [ ]:
# Execute this to save new versions of the notebook
jovian.commit(project="feature-extraction")

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from skimage.io import imread, imshow

image = imread('https://th.bing.com/th/id/OIP.HMwiJdVhjdIaaqh536gjGAHaHa?w=182&h=182&c=7&o=5&pid=1.7',as_gray=True)
imshow(image)

In [5]:
#checking image shape 
image.shape, image

((182, 182),
 array([[0.96660275, 0.96268118, 0.95875961, ..., 0.97166314, 0.97558471,
         0.98147843],
        [0.96660275, 0.96268118, 0.95875961, ..., 0.97166314, 0.97166314,
         0.98147843],
        [0.96660275, 0.96268118, 0.95875961, ..., 0.96774157, 0.96774157,
         0.97755686],
        ...,
        [0.20614588, 0.20614588, 0.20222431, ..., 0.25932863, 0.28285804,
         0.27109333],
        [0.21398902, 0.20614588, 0.19830275, ..., 0.2632502 , 0.29070118,
         0.2750149 ],
        [0.23359686, 0.21398902, 0.19045961, ..., 0.2632502 , 0.29462275,
         0.27893647]]))

In [6]:
'''
The following code is to Read the Image Data
'''

from skimage.io import imread, imshow
image = imread('https://th.bing.com/th/id/OIP.HMwiJdVhjdIaaqh536gjGAHaHa?w=182&h=182&c=7&o=5&pid=1.7', as_gray=True)

'''Uncomment the following lines of code to display image in Jupyter notebook'''

# import matplotlib.pyplot as plt
# %matplotlib inline
#imshow(image)

#checking image shape 
print('Shape of the image is = ',image.shape)

# image matrix
print('\n\nImage matrix\n\n',image)

Shape of the image is =  (182, 182)


Image matrix

 [[0.96660275 0.96268118 0.95875961 ... 0.97166314 0.97558471 0.98147843]
 [0.96660275 0.96268118 0.95875961 ... 0.97166314 0.97166314 0.98147843]
 [0.96660275 0.96268118 0.95875961 ... 0.96774157 0.96774157 0.97755686]
 ...
 [0.20614588 0.20614588 0.20222431 ... 0.25932863 0.28285804 0.27109333]
 [0.21398902 0.20614588 0.19830275 ... 0.2632502  0.29070118 0.2750149 ]
 [0.23359686 0.21398902 0.19045961 ... 0.2632502  0.29462275 0.27893647]]


In [7]:
'''
Grayscale Pixel Values as Features
'''
# importing library and read the image 
import numpy as np
from skimage.io import imread, imshow
image = imread('https://th.bing.com/th/id/OIP.HMwiJdVhjdIaaqh536gjGAHaHa?w=182&h=182&c=7&o=5&pid=1.7', as_gray=True) 

# shape of the image
print('\n\nShape of the image = ',image.shape)

# create features
features = np.reshape(image, (182*182))

# shape of feature array
print('\n\nShape of the feature array = ',features.shape)

print('\n\nFeature Array\n\n',features)



Shape of the image =  (182, 182)


Shape of the feature array =  (33124,)


Feature Array

 [0.96660275 0.96268118 0.95875961 ... 0.2632502  0.29462275 0.27893647]


In [1]:
# Execute this to save new versions of the notebook
jovian.commit(project="feature-extraction")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "arpnabarekan111/feature-extraction" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/arpnabarekan111/feature-extraction


'https://jovian.ai/arpnabarekan111/feature-extraction'